# -*- coding: utf-8 -*-
"""Confirm that ``abm_s_population.s_protein_steady_state`` (the extracted
"lines 266-end" closed form) reproduces the normal alpha-syn growth of

    magnesium2400/SIR_simulator @ speedup_0.2 : SIRsimulator4.m, lines 68-109

on the repo's own 42-region reference data, and compare the result against
``origresults.mat`` (the output of main.py / main.m).

What this script does
---------------------
1. Loads the converted (params, Snca, GBA) pickles produced by
   ``convert_sir_simulator_data.py``.
2. Reproduces the SIRsimulator4.m pre-processing (lines 34-57) *exactly*
   -- prob_stay mix, row-normalisation, MATLAB ``zscore`` (ddof=1),
   ``normcdf`` -- to build ``weights`` / ``sconnMov`` / ``clearance`` /
   ``synthesis``.
3. Calls ``s_protein_steady_state`` -> writes ``s_region_closed_form.csv`` and
   ``s_edge_closed_form.csv`` (the same files ``abm_s_population.py`` writes).
4. Independently runs the *iterative* growth loop (SIRsimulator.m lines 71-95)
   to tight convergence as a ground-truth steady state.
5. Compares closed form vs (a) the tight iterative steady state and
   (b) ``origresults.mat``'s ``Rnor0``.

Note on origresults.mat: it was generated by the iterative loop with the loose
stopping rule ``abs(Rnor - Rtmp) < 1e-7 * Rtmp``, i.e. it is an *under-converged*
snapshot, not the true fixed point.  So the meaningful equivalence check is
(a) -- closed form vs a properly converged simulation.  (b) is reported for
completeness and is expected to differ at the ~0.3% level.

Usage:
    python verify_closed_form_vs_matlab.py \
        --repo /scratch/vnathan/SIR_simulator_mehul \
        --ref-dir ./sir_simulator_ref \
        --parcellation 42regions --sc sc35
"""

import argparse
import os
import pickle

import numpy as np
import pandas as pd
import scipy.io as sio
import scipy.sparse
from scipy.stats import norm

# --- parameters from main.m -------------------------------------------------
V = 1.0
DT = 0.01
PROB_STAY = 0.5
SYN_CONTROL_IS_ROISIZE = True   # main.m: syn_control = ROIsize


def matlab_zscore(x):
    """MATLAB ``zscore`` normalises by N-1 (sample std)."""
    x = np.asarray(x, dtype=float)
    return (x - x.mean()) / x.std(ddof=1)


def preprocess(sconn_den, sconn_len, roi_size, gba, snca):
    """SIRsimulator4.m lines 34-57."""
    sconn_den = sconn_den.astype(float).copy()
    sconn_len = sconn_len.astype(float).copy()
    n = sconn_den.shape[0]
    np.fill_diagonal(sconn_den, 0.0)
    np.fill_diagonal(sconn_len, 0.0)

    with np.errstate(divide="ignore"):
        sconn_mov = V / sconn_len * DT
    sconn_mov[sconn_len == 0] = 0.0

    weights = sconn_den.copy()
    weights = (1.0 - PROB_STAY) * weights + PROB_STAY * np.diag(weights.sum(axis=1))
    weights = weights / weights.sum(axis=1, keepdims=True) * DT
    np.fill_diagonal(weights, 0.0)

    clearance_rate = norm.cdf(matlab_zscore(gba))
    synthesis_rate = norm.cdf(matlab_zscore(snca))
    clearance = np.exp(-clearance_rate * DT)
    synthesis = synthesis_rate * roi_size * DT
    return weights, sconn_mov, clearance, synthesis


def markov_steady_state(weights, sconnMov, clearance, synthesis):
    """Closed-form normal alpha-syn steady state.

    Mirror of the closed-form block in ``abm_s_population.py`` __main__ (kept in
    sync by hand).  Equivalent to SIRsimulator4.m lines 68-109.
    """
    N = weights.shape[0]

    M_RR = np.diag(1 - weights.sum(axis=1))
    M_PP = np.diag(np.where(sconnMov.flatten(order="F") > 0, 1, 0) - sconnMov.flatten(order="F"))

    list_1_n = list(range(0, N))
    rows_i, cols_j = np.meshgrid(list_1_n, list_1_n, indexing="ij")
    list_1_n2 = list(range(0, N**2))
    M_RP = scipy.sparse.coo_matrix((weights.flatten(order="F"), (list_1_n2, rows_i.flatten(order="F"))), shape=(N**2, N)).toarray()
    M_PR = scipy.sparse.coo_matrix((sconnMov.flatten(order="F"), (cols_j.flatten(order="F"), list_1_n2)), shape=(N, N**2)).toarray()

    C_diag = np.diag(clearance)
    M = np.vstack((np.hstack((C_diag @ M_RR, C_diag @ M_PR)),
                  np.hstack((M_RP, M_PP))))

    B = np.concatenate((synthesis, np.zeros(N**2)))
    X, resid, rank, s = np.linalg.lstsq((np.eye(N + N**2) - M), B, rcond=None)
    Rnor0 = X[0:N]
    Pnor0 = np.reshape(X[N:N + N**2], (N, N), order="F")
    return Rnor0, Pnor0


def iterative_steady_state(weights, sconn_mov, clearance, synthesis,
                           rtol=1e-13, max_iter=50_000_000):
    """SIRsimulator.m lines 71-95, run to (near) machine convergence."""
    n = weights.shape[0]
    r = np.zeros(n)
    p = np.zeros((n, n))
    for t in range(max_iter):
        r_prev = r.copy()
        mov_drt = r[:, None] * weights          # region -> edge
        mov_out = p * sconn_mov                 # edge -> region
        p = p - mov_out + mov_drt
        r = r + mov_out.sum(axis=0) - mov_drt.sum(axis=1)
        r = r * clearance + synthesis
        if np.all(np.abs(r - r_prev) < rtol * np.maximum(np.abs(r_prev), 1e-300)):
            return r, p, t + 1
    return r, p, max_iter


def report(name, a, b):
    a = np.asarray(a).ravel()
    b = np.asarray(b).ravel()
    abs_err = np.abs(a - b)
    # scale-relative error: max abs error over the scale of the reference
    rel_err = abs_err.max() / max(np.abs(b).max(), 1e-300)
    print(f"  {name:<42} max|Δ| = {abs_err.max():.3e}   "
          f"rel (vs scale) = {rel_err:.3e}")
    return abs_err.max(), rel_err


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--repo", default="/scratch/vnathan/SIR_simulator_mehul")
    p.add_argument("--ref-dir", default="./sir_simulator_ref",
                   help="output dir of convert_sir_simulator_data.py")
    p.add_argument("--parcellation", default="42regions")
    p.add_argument("--sc", default="sc35")
    return p.parse_args()


def main():
    args = parse_args()

    params_path = os.path.join(args.ref_dir,
                               f"params_{args.parcellation}_{args.sc}.pkl")
    with open(params_path, "rb") as f:
        params = pickle.load(f)
    snca = pd.read_pickle(os.path.join(args.ref_dir, "Snca.pkl"))
    gba = pd.read_pickle(os.path.join(args.ref_dir, "GBA.pkl"))

    sources = params["sources"]
    sconn_den = np.asarray(params["weights"], dtype=float)
    sconn_len = np.asarray(params["distance"], dtype=float)
    roi_size = np.asarray(params["region_size"], dtype=float).ravel()
    snca_v = snca.loc[sources, "Snca"].to_numpy()
    gba_v = gba.loc[sources, "GBA"].to_numpy()

    weights, sconn_mov, clearance, synthesis = preprocess(
        sconn_den, sconn_len, roi_size, gba_v, snca_v
    )

    # (1) closed form -- the block under test
    r_closed, p_closed = markov_steady_state(weights, sconn_mov,
                                             clearance, synthesis)
    pd.DataFrame(r_closed).to_csv("s_region_closed_form.csv")
    pd.DataFrame(p_closed).to_csv("s_edge_closed_form.csv")
    print("\nwrote s_region_closed_form.csv, s_edge_closed_form.csv")

    # (2) iterative ground truth
    print("\nrunning iterative growth loop to tight convergence "
          "(this takes a moment)...")
    r_iter, p_iter, n_iter = iterative_steady_state(
        weights, sconn_mov, clearance, synthesis
    )
    print(f"  converged after {n_iter} iterations")

    # (2b) iterative with the *loose* stopping rule main.m/SIRsimulator.m used
    r_loose, _, n_loose = iterative_steady_state(
        weights, sconn_mov, clearance, synthesis, rtol=1e-7
    )
    print(f"  loose (1e-7) stopping rule: {n_loose} iterations")

    # (3) origresults.mat
    orig = sio.loadmat(os.path.join(args.repo, "origresults.mat"))
    r_orig = orig["Rnor0"].ravel()

    print("\n--- equivalence checks -------------------------------------------")
    e1_a, e1_r = report("closed form  vs  iterative steady state", r_closed, r_iter)
    report("closed-form P vs  iterative steady-state P", p_closed, p_iter)
    e2_a, e2_r = report("closed form  vs  origresults.mat Rnor0", r_closed, r_orig)
    report("iterative (loose 1e-7)  vs  origresults.mat", r_loose, r_orig)
    report("iterative (tight)  vs  origresults.mat", r_iter, r_orig)

    print("\n--- verdict -----------------------------------------------------")
    ok = (e1_r < 1e-4)
    print(f"  closed form == properly-converged simulation : "
          f"{'PASS' if ok else 'FAIL'}  (max rel {e1_r:.2e}, tol 1e-4)")
    print(f"  closed form vs origresults.mat               : max abs {e2_a:.2f}"
          f"  ({e2_r*100:.2f}%)")
    print( "    -> origresults.mat is an under-converged snapshot "
           "(loose 1e-7 step rule);")
    print( "       the closed form matches the true fixed point instead.")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
